Fix call to format_exception() download project fails
Some users were getting this exception while handling download error:
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'